"""render_tasks

Revision ID: 9c1ffdfee6d6
Revises: 5c7b8b836d79
Create Date: 2026-06-04 16:43:16.541313

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1ffdfee6d6'
down_revision: str | None = '5c7b8b836d79'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('render_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('codec', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_props', sa.JSON(), nullable=False),
    sa.Column('output_path', sa.String(length=1024), nullable=False),
    sa.Column('error', sa.String(length=2048), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_tasks_created_at'), 'render_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_render_tasks_status'), 'render_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_render_tasks_user_id'), 'render_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_render_tasks_user_id'), table_name='render_tasks')
    op.drop_index(op.f('ix_render_tasks_status'), table_name='render_tasks')
    op.drop_index(op.f('ix_render_tasks_created_at'), table_name='render_tasks')
    op.drop_table('render_tasks')
    # ### end Alembic commands ###
